// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZFXwR0PslcNSLwokTXbxwl_zSW_Cy_g',
    appId: '1:687140392559:web:e752d31a5d76b44eb0079a',
    messagingSenderId: '687140392559',
    projectId: 'mood-tracker-5f039',
    authDomain: 'mood-tracker-5f039.firebaseapp.com',
    storageBucket: 'mood-tracker-5f039.firebasestorage.app',
    measurementId: 'G-E1K0C5YCY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcywUdfmIZDeLxvkfHNOWHp5TvtqsLrc',
    appId: '1:687140392559:android:94662af480502bebb0079a',
    messagingSenderId: '687140392559',
    projectId: 'mood-tracker-5f039',
    storageBucket: 'mood-tracker-5f039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaydxdW3Y1z29p9Tt2cbRF2W3zx033BQE',
    appId: '1:687140392559:ios:840acd3411dcda1eb0079a',
    messagingSenderId: '687140392559',
    projectId: 'mood-tracker-5f039',
    storageBucket: 'mood-tracker-5f039.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaydxdW3Y1z29p9Tt2cbRF2W3zx033BQE',
    appId: '1:687140392559:ios:840acd3411dcda1eb0079a',
    messagingSenderId: '687140392559',
    projectId: 'mood-tracker-5f039',
    storageBucket: 'mood-tracker-5f039.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZFXwR0PslcNSLwokTXbxwl_zSW_Cy_g',
    appId: '1:687140392559:web:07cfdd6ceb052e63b0079a',
    messagingSenderId: '687140392559',
    projectId: 'mood-tracker-5f039',
    authDomain: 'mood-tracker-5f039.firebaseapp.com',
    storageBucket: 'mood-tracker-5f039.firebasestorage.app',
    measurementId: 'G-S0Y4GGE1N8',
  );
}